### ISSUE TITLE
egorm 的 BuildQuery 支持构建  'or' 连接符的sql语句吗?

### ISSUE THREAD

**Issue by FangPengbo** [ego-component/egorm#11]
**Describe the solution you'd like**
buildquery.go:86
BuildQuery 函数 看起来仅支持构建 `and` 连接符的sql, 能否支持 `or` 呢

**Describe alternatives you've considered**
```
   Cond struct {
   // Cs MySQL中条件连接符，常量限制于 [AND,OR..]
   Cs Constant
   // Op MySQL中查询条件，如like,=,in
   Op string
   // Val 查询条件对应的值
   Val interface{}
	}
```

**Comment by askuy** [comment]
已支持：https://github.com/ego-component/egorm/pull/14
