### ISSUE TITLE
更新最新版本后，出现不兼容问题

### ISSUE THREAD

**Issue by zhiqiu1995** [ego-component/egorm#15]
# gorm.io/plugin/dbresolver
..\..\..\pkg\mod\gorm.io\plugin\dbresolver@v1.1.0\dbresolver.go:139:18: cannot use map[string]gorm.Stmt{} (value of type map[string]gorm.Stmt) as map[string]*gorm.Stmt value in struct literal
# github.com/glebarez/sqlite
..\..\..\pkg\mod\github.com\glebarez\sqlite@v1.4.3\sqlite.go:101:22: invalid operation: limit.Limit > 0 (mismatched types *int and untyped int)
..\..\..\pkg\mod\github.com\glebarez\sqlite@v1.4.3\sqlite.go:102:24: invalid operation: limit.Limit <= 0 (mismatched types *int and untyped int)
..\..\..\pkg\mod\github.com\glebarez\sqlite@v1.4.3\sqlite.go:103:21: cannot use -1 (untyped int constant) as *int value in assignment
..\..\..\pkg\mod\github.com\glebarez\sqlite@v1.4.3\sqlite.go:106:39: cannot use limit.Limit (variable of type *int) as int value in argument to strconv.Itoa

**Comment by askuy** [comment]
https://github.com/ego-component/egorm/issues/10
看下这个issue
